### ISSUE TITLE
BetterDiscord plugin compatibility

### ISSUE THREAD

**Issue by erkinalp** [spacebarchat/fosscord-web-client#152]

**Comment by samuelscheit** [comment]
won't fix
The plugin system of the fosscord client will be completely different to the current better discord system (and being backwards compatible would result in security risks).
We will have our own plugin sdk:

> Plugins are executed in their environment to prevent security issues
Plugins can create their own UI and loaded in a separate view (similar to vscode extensions)
Plugins can access the component Api and therefore extend the client UI
Plugins can access the WebSocket Connection/Rest API and intercept/transform events
Plugins are restricted and can only do actions with the corresponding permission
Plugins should be accessible through a store that needs to verify the plugins (with dev options to sideload plugins/add other stores)
