### ISSUE TITLE
Can't register or login as hcaptcha tries to use host=localhost

### ISSUE THREAD

**Issue by Rosentti** [spacebarchat/fosscord-web-client#96]

**Comment by samuelscheit** [comment]
hcaptcha should be disabled by default?

**Comment by Rosentti** [comment]
It doesn't seem like it...

**Comment by samuelscheit** [comment]
can you provide more information about your environment

**Comment by Rosentti** [comment]
Arch Linux, "installed" using "npm i", started using "npm start".
Tried to login/register to discord.com or fosscord.com, but the captcha comes up

**Comment by samuelscheit** [comment]
we can't change anything about the discord.com hcaptcha key and can only fix this on the desktop client, not the web app

**Comment by samuelscheit** [comment]
fosscord.com shouldn't be restricted to a domain tho
